"\nDjango settings for cabain project.\n\nGenerated by 'django-admin startproject' using Django 4.1.\n\nFor more information on this file, see\nhttps://docs.djangoproject.com/en/4.1/topics/settings/\n\nFor the full list of settings and their values, see\nhttps://docs.djangoproject.com/en/4.1/ref/settings/\n"
from pathlib import Path
import os
import pymysql
pymysql.install_as_MySQLdb()
PASSWORD_RESET_COMPLETE_TEMPLATE = 'index.html'
BASE_DIR=Path(__file__).resolve().parent.parent
LOGIN_REDIRECT_URL='/menu_principal/'
LOGIN_URL='/cuenta/login/'
SECRET_KEY='django-insecure-+1+o8as375p_ogyz4)_()cw+k%@13p3rgn43kvq@%!me63j)41'
DEBUG=True
ALLOWED_HOSTS=[]
MESSAGE_STORAGE='django.contrib.messages.storage.cookie.CookieStorage'
INSTALLED_APPS=['cabin_APP','django.contrib.admin','django.contrib.auth','django.contrib.contenttypes','django.contrib.sessions','django.contrib.messages','django.contrib.staticfiles','django.contrib.humanize','crispy_forms']
MIDDLEWARE=['htmlmin.middleware.HtmlMinifyMiddleware','htmlmin.middleware.MarkRequestMiddleware','django.middleware.security.SecurityMiddleware','django.contrib.sessions.middleware.SessionMiddleware','django.middleware.common.CommonMiddleware','django.middleware.csrf.CsrfViewMiddleware','django.contrib.auth.middleware.AuthenticationMiddleware','django.contrib.messages.middleware.MessageMiddleware','django.middleware.clickjacking.XFrameOptionsMiddleware']
HTML_MINIFY=True
ROOT_URLCONF='cabain.urls'
TEMPLATES=[{'BACKEND':'django.template.backends.django.DjangoTemplates','DIRS':[os.path.join(BASE_DIR,'templates')],'APP_DIRS':True,'OPTIONS':{'context_processors':['django.template.context_processors.debug','django.template.context_processors.request','django.contrib.auth.context_processors.auth','django.contrib.messages.context_processors.messages']}}]
WSGI_APPLICATION='cabain.wsgi.application'
DATABASES={'default':{'ENGINE':'django.db.backends.mysql','NAME':'cabinsproyect','USER':'root','PASSWORD':'','OPTIONS':{'sql_mode':'STRICT_TRANS_TABLES'}}}
AUTH_PASSWORD_VALIDATORS=[{'NAME':'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},{'NAME':'django.contrib.auth.password_validation.MinimumLengthValidator'},{'NAME':'django.contrib.auth.password_validation.CommonPasswordValidator'},{'NAME':'django.contrib.auth.password_validation.NumericPasswordValidator'}]
LANGUAGE_CODE='es-esp'
TIME_ZONE='UTC'
USE_I18N=True
USE_TZ=True
STATIC_URL='static/'
STATICFILES_DIRS=[os.path.join(BASE_DIR,'static')]
CRISPY_TEMPLATE_PACK='bootstrap4'
DEFAULT_AUTO_FIELD='django.db.models.BigAutoField'
TBK_COMMERCE_CODE='597055555532'
TBK_API_KEY='579B532A7440BB0C9079DED94D31EA1615BACEB56610332264630D42D0A36B1C'
TBK_CERT_PATH='/ruta/al/archivo/certificado/transbank.pem'
TBK_KEY_PATH='/ruta/al/archivo/llave/transbank.key'
EMAIL_BACKEND='django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST='smtp.gmail.com'
EMAIL_PORT=587
EMAIL_USE_TLS=True
EMAIL_HOST_USER='dominatuproyecto@gmail.com'
EMAIL_HOST_PASSWORD='jemu bioh kjex xtar'